
all:
	@(cd dns; make)
	@(cd fiber; make)
	@(cd httpd; make)
	@(cd httpd2; make)
	@(cd server; make)
	@(cd sleep; make)

cl clean:
	@(cd dns; make clean)
	@(cd fiber; make clean)
	@(cd httpd; make clean)
	@(cd httpd2; make clean)
	@(cd server; make clean)
	@(cd sleep; make clean)
